### ISSUE TITLE
flickering when using with react navigation bottom bar 

### ISSUE THREAD

**Issue by 25khattab** [mateusz1913/react-native-avoid-softinput#181] opened 2023-09-11 23:21 UTC
### Environment

Library version: 4.0.1
OS version: pixel 7 android 13

### Affected platforms

- [X] Android
- [x] iOS - not tested

### Current behavior

When moving between the screen a flicker happens and its very visible and annoying and I donot know the reason 

only appears when using  `AvoidSoftInput.setShouldMimicIOSBehavior(true);`

https://github.com/mateusz1913/react-native-avoid-softinput/assets/53271078/b27c4bc4-e153-41b2-ade5-85678d79f919

when I use `AvoidSoftInput.setShouldMimicIOSBehavior(false);`

it doesn't happen but also a flick happens 

when opening and closing the keyboard

https://github.com/mateusz1913/react-native-avoid-softinput/assets/53271078/c824ed13-717a-45d9-9904-e9a9ac94bc39

### Expected behavior

while  `AvoidSoftInput.setShouldMimicIOSBehavior(true);` it should't do that flicker

### Reproduction

https://github.com/25khattab/react-native-template

**Comment by 25khattab** [comment] 2023-09-14 18:31
@mateusz1913  when you have time please, thank you

**Comment by mateusz1913** [comment] 2023-09-15 08:01
Hey @25khattab, sorry for delay and **thanks for proper reproduction repo** 🚀

I managed to reproduce it, but I need to dig deeper and will get back to you later today or on weekend

**Comment by 25khattab** [comment] 2023-09-16 13:31
Thank you @mateusz1913,
another thing I noticed The animation doesn't work when mimic ios it just feels laggy Im on pixel 7 running 90 hz

**Comment by mateusz1913** [comment] 2023-09-16 17:48
Hey @25khattab, it seems that the problem is caused by incorrectly handled safe area. I made [a PR](https://github.com/25khattab/react-native-template/pull/1) in your repo and I'll close this issue as it's not related to the library.

Regarding the animation, if you feel that it doesn't work at all, open new issue and provide a short recording (I assume that reproduction repo will be the same as here), thx!

**Closed by mateusz1913** 2023-09-16 17:48 UTC
Labels: bug
